
import com.android.build.gradle.BaseExtension
import org.gradle.api.Plugin
import org.gradle.api.Project
import org.gradle.kotlin.dsl.configure
import java.io.FileNotFoundException
import java.util.Properties

/**
 * Single source of truth for application environments and versioning across Android and iOS.
 *
 * Responsibilities:
 *   - Reads [versions.properties] from the project root (same file bumped by release pipelines).
 *   - Defines the full list of environments (prod, mock) and their platform-specific settings.
 *   - Android: configures [productFlavors] + applies [versionCode]/[versionName] from properties.
 *   - iOS: generates `.xcconfig` files under [iosApp/Config/] so Xcode picks the right
 *          version, bundle id, and [SWIFT_ACTIVE_COMPILATION_CONDITIONS] per scheme.
 *   - Registers a [generateIosEnvConfig] task that runs before iOS framework builds.
 *
 * Usage: apply `gasguru.environments` (alias [gasguru-flavors]) to [:app] and [:composeApp].
 */
class EnvironmentsConventionPlugin : Plugin<Project> {

    private data class Environment(
        val name: String,
        val bundleSuffix: String?,
        val nameSuffix: String?,
        val versionNameSuffix: String?,
        val isMock: Boolean,
    )

    override fun apply(project: Project) {
        val versionProps = readVersionProperties(project)
        val versionName = buildVersionName(versionProps)
        val versionCode = versionProps.getProperty("versionCode").trim().toInt()

        val environments = listOf(
            Environment(
                name = "prod",
                bundleSuffix = null,
                nameSuffix = null,
                versionNameSuffix = null,
                isMock = false,
            ),
            Environment(
                name = "mock",
                bundleSuffix = ".mock",
                nameSuffix = " Mock",
                versionNameSuffix = "-mock",
                isMock = true,
            ),
        )

        configureAndroid(project, environments, versionCode, versionName)
        registerGenerateIosEnvConfigTask(project, environments, versionCode, versionName)
    }

    // ── Android ──────────────────────────────────────────────────────────────

    private fun configureAndroid(
        project: Project,
        environments: List<Environment>,
        versionCode: Int,
        versionName: String,
    ) {
        project.plugins.withId("com.android.application") {
            project.extensions.configure<BaseExtension> {
                defaultConfig {
                    this.versionCode = versionCode
                    this.versionName = versionName
                }
                flavorDimensions("environment")
                productFlavors {
                    environments.forEach { env ->
                        create(env.name) {
                            dimension = "environment"
                            env.bundleSuffix?.let { applicationIdSuffix = it }
                            env.versionNameSuffix?.let { versionNameSuffix = it }
                        }
                    }
                }
            }
        }
    }

    // ── iOS xcconfig generation ───────────────────────────────────────────────

    private fun registerGenerateIosEnvConfigTask(
        project: Project,
        environments: List<Environment>,
        versionCode: Int,
        versionName: String,
    ) {
        val baseApplicationId = "com.gasguru"
        val baseAppName = "GasGuru"

        val generateTask = project.tasks.register("generateIosEnvConfig") {
            group = "gasguru"
            description = "Generates per-environment .xcconfig files for iOS builds."

            val configDir = project.rootProject.file("iosApp/Config")
            outputs.dir(configDir)

            doLast {
                configDir.mkdirs()
                environments.forEach { env ->
                    val bundleId = baseApplicationId + (env.bundleSuffix ?: "")
                    val appName = baseAppName + (env.nameSuffix ?: "")
                    val compilationConditions = if (env.isMock) "$(inherited) MOCK" else "$(inherited)"

                    val xcconfig = buildString {
                        appendLine("// Auto-generated by EnvironmentsConventionPlugin — do not edit manually.")
                        appendLine("// Source of truth: versions.properties + EnvironmentsConventionPlugin.kt")
                        appendLine()
                        appendLine("MARKETING_VERSION=$versionName")
                        appendLine("CURRENT_PROJECT_VERSION=$versionCode")
                        appendLine("PRODUCT_BUNDLE_IDENTIFIER=$bundleId")
                        appendLine("PRODUCT_NAME=$appName")
                        if (env.isMock) {
                            appendLine("GASGURU_ENV=mock")
                        } else {
                            appendLine("GASGURU_ENV=prod")
                        }
                        appendLine("SWIFT_ACTIVE_COMPILATION_CONDITIONS=$compilationConditions")
                    }

                    configDir.resolve("gasguru-${env.name}.xcconfig").writeText(xcconfig)
                }
            }
        }

        // Run before any iOS framework embed/sign tasks so Xcode always gets fresh xcconfigs.
        project.tasks.configureEach {
            if (name == "embedAndSignAppleFrameworkForXcode" || name == "syncFramework") {
                dependsOn(generateTask)
            }
        }
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    private fun readVersionProperties(project: Project): Properties {
        val propsFile = project.rootProject.file("versions.properties")
        if (!propsFile.exists()) throw FileNotFoundException("versions.properties not found at ${propsFile.absolutePath}")
        return Properties().apply { propsFile.inputStream().use { load(it) } }
    }

    private fun buildVersionName(props: Properties): String {
        val major = props.getProperty("versionMajor").trim()
        val minor = props.getProperty("versionMinor").trim()
        val patch = props.getProperty("versionPatch").trim()
        return "$major.$minor.$patch"
    }
}
