name: iosApp
options:
  deploymentTarget:
    iOS: "15.0"
  xcodeVersion: "16"
targets:
  iosApp:
    type: application
    platform: iOS
    sources:
      - path: iosApp
    info:
      path: iosApp/Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.gasguru.iosApp
        SWIFT_VERSION: "5.0"
        TARGETED_DEVICE_FAMILY: "1,2"
