package com.gasguru.core.supabase.model

data class NetworkPriceFuelStation(
    val bioEthanolPercentage: String,
    val esterMethylPercentage: String,
    val postalCode: String,
    val direction: String,
    val schedule: String,
    val idAutonomousCommunity: String,
    val idServiceStation: String,
    val idMunicipality: String,
    val idProvince: String,
    val latitude: String,
    val locality: String,
    val longitudeWGS84: String,
    val margin: String,
    val municipality: String,
    val priceBiodiesel: String,
    val priceBioEthanol: String,
    val priceGasNaturalCompressed: String,
    val priceLiquefiedNaturalGas: String,
    val priceLiquefiedPetroleumGas: String,
    val priceGasoilA: String,
    val priceGasoilB: String,
    val priceGasoilPremium: String,
    val priceGasoline95E10: String,
    val priceGasoline95E5: String,
    val priceGasoline95E5Premium: String,
    val priceGasoline98E10: String,
    val priceGasoline98E5: String,
    val priceHydrogen: String,
    val priceAdblue: String,
    val province: String,
    val referral: String,
    val brandStation: String,
    val typeSale: String,
)
