package com.gasguru.core.supabase.model

fun SupabaseFuelStation.asNetworkModel() = NetworkPriceFuelStation(
    bioEthanolPercentage = bioEthanolPercentage,
    esterMethylPercentage = esterMethylPercentage,
    postalCode = postalCode,
    direction = direction,
    schedule = schedule,
    idAutonomousCommunity = idAutonomousCommunity,
    idServiceStation = idServiceStation,
    idMunicipality = idMunicipality,
    idProvince = idProvince,
    latitude = latitude.toString(),
    locality = locality,
    longitudeWGS84 = longitudeWGS84.toString(),
    margin = margin,
    municipality = municipality,
    priceBiodiesel = priceBiodiesel?.toString() ?: "",
    priceBioEthanol = priceBioEthanol?.toString() ?: "",
    priceGasNaturalCompressed = priceGasNaturalCompressed?.toString() ?: "",
    priceLiquefiedNaturalGas = priceLiquefiedNaturalGas?.toString() ?: "",
    priceLiquefiedPetroleumGas = priceLiquefiedPetroleumGas?.toString() ?: "",
    priceGasoilA = priceGasoilA?.toString() ?: "",
    priceGasoilB = priceGasoilB?.toString() ?: "",
    priceGasoilPremium = priceGasoilPremium?.toString() ?: "",
    priceGasoline95E10 = priceGasoline95E10?.toString() ?: "",
    priceGasoline95E5 = priceGasoline95E5?.toString() ?: "",
    priceGasoline95E5Premium = priceGasoline95E5Premium?.toString() ?: "",
    priceGasoline98E10 = priceGasoline98E10?.toString() ?: "",
    priceGasoline98E5 = priceGasoline98E5?.toString() ?: "",
    priceHydrogen = priceHydrogen?.toString() ?: "",
    priceAdblue = priceAdblue?.toString() ?: "",
    province = province,
    referral = referral,
    brandStation = brandStation,
    typeSale = typeSale,
)
