package com.albrivas.fuelpump.core.domain.model

import com.albrivas.fuelpump.core.model.data.FuelStationBrandsType

data class FuelStationDomain(
    val bioEthanolPercentage: String,
    val esterMethylPercentage: String,
    val postalCode: String,
    val direction: String,
    val schedule: String,
    val idAutonomousCommunity: String,
    val idServiceStation: Int,
    val idMunicipality: String,
    val idProvince: String,
    val latitude: String,
    val locality: String,
    val longitudeWGS84: String,
    val margin: String,
    val municipality: String,
    val priceGasoilA: String,
    val priceGasoilB: String,
    val priceGasoilPremium: String,
    val priceGasoline95_E10: String,
    val priceGasoline95_E5: String,
    val priceGasoline95_E5_Premium: String,
    val priceGasoline98_E10: String,
    val priceGasoline98_E5: String,
    val priceHydrogen: String,
    val province: String,
    val referral: String,
    val brandStationName: String,
    val brandStationBrandsType: FuelStationBrandsType,
    val typeSale: String
)

fun previewFuelStationDomain() =  FuelStationDomain(
    "",
    "",
    "",
    "",
    "",
    "",
    1,
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "1,65",
    "",
    "",
    "",
    "",
    "",
    "",
    "REPSOL",
    FuelStationBrandsType.REPSOL,
    ""
)

